services:
  backend:
    build: 
      context: ./flask-back
      dockerfile: Dockerfile.back
    container_name: backend
    ports:
      - "5000:5000"
    env_file:
      - flask-back/backend.env
    networks:
      - app_network

  frontend:
    build: 
      context: ./express-front
      dockerfile: Dockerfile.front
    container_name: frontend
    ports:
      - "3000:3000"
    env_file:
      - express-front/frontend.env
    networks:
      - app_network

networks:
  app_network:
    driver: bridge